version: "3"
services:
  nginx-php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./var/www/html
    ports:
      - "80:80"
    networks:
      - mynetwork

networks:
  mynetwork:
